import { env } from "process";

export const API_URL            = process.env.NEXT_PUBLIC_API_BASE_URL as string;
export const API_MOCKING        = process.env.NEXT_PUBLIC_API_MOCKING === 'true';
export const IS_DEVELOPMENT     = env.nodeEnv === 'development';
export const IS_TEST            = env.nodeEnv === 'test';
export const IS_PRODUCTION      = env.nodeEnv === 'production';
export const IS_BROWSER         = typeof window !== 'undefined';
export const IS_SERVER          = typeof window === 'undefined';
export const DRAWER_WIDTH       = 240;

export const AUTH_REGISTER_PATH          = '/api/auth/register';
export const AUTH_LOGIN_PATH             = '/api/auth/login';
export const AUTH_LOGOUT_PATH            = '/api/auth/logout';
export const AUTH_REFRESH_TOKEN_PATH     = '/api/auth/refresh';
export const PERMISSION_CREATE_PATH      = '/api/permission';
export const PERMISSION_READ_PATH        = '/api/permission';
export const PERMISSION_READ_BYID_PATH   = '/api/permission/';
export const PERMISSION_UPDATE_PATH      = '/api/permission/';
export const PERMISSION_DELETE_PATH      = '/api/permission/';
export const ROLE_CREATE_PATH            = '/api/role';
export const ROLE_READ_PATH              = '/api/role';
export const ROLE_READ_BYID_PATH         = '/api/role/';
export const ROLE_UPDATE_PATH            = '/api/role/';
export const ROLE_DELETE_PATH            = '/api/role/';
export const USER_CREATE_PATH            = '/api/user';
export const USER_READ_PATH              = '/api/user';
export const USER_READ_BYID_PATH         = '/api/user/';
export const USER_UPDATE_PATH            = '/api/user/';
export const USER_DELETE_PATH            = '/api/user/';
export const USER_RESET_PASSWORD_PATH    = '/api/user/reset/';
export const SHAPE_CREATE_PATH           = '/api/shape';
export const SHAPE_READ_PATH             = '/api/shape';
export const SHAPE_READ_BYID_PATH        = '/api/shape/';
export const SHAPE_UPDATE_PATH           = '/api/shape/';
export const SHAPE_DELETE_PATH           = '/api/shape/';
export const CATEGORY_CREATE_PATH        = '/api/category';
export const CATEGORY_READ_PATH          = '/api/category';
export const CATEGORY_READ_BYID_PATH     = '/api/category/';
export const CATEGORY_UPDATE_PATH        = '/api/category/';
export const CATEGORY_DELETE_PATH        = '/api/category/';
export const THERAPYCLASS_CREATE_PATH    = '/api/therapy-class';
export const THERAPYCLASS_READ_PATH      = '/api/therapy-class';
export const THERAPYCLASS_READ_BYID_PATH = '/api/therapy-class/';
export const THERAPYCLASS_UPDATE_PATH    = '/api/therapy-class/';
export const THERAPYCLASS_DELETE_PATH    = '/api/therapy-class/';